# AD-Capital Approval Node
#
# This Resource definition has been modifed to instrument the Approval application
# with the lastest AppDynamics Java Agent using the initialization container method
#
# Note this POD is named approval-v2
#
# The configuration map have been named as follows:
# adcap-approval
# adcap-approcal-appdynamics
# appdynamics-common
# appdynamics-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-v2
  labels:
    app: approval-v2
    name: approval-v2
    keel.sh/policy: force
    keel.sh/trigger: poll
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approval-v2
  strategy:
    type: Recreate
  template:
    metadata:
      name: approval-v2
      labels:
        app: approval-v2
    spec:
      containers:
      - name: approval-v2
        image: lincharles/adcapital-tomcat:latest
        imagePullPolicy: Always
        # Modification-1 - Add Configuration Maps Environment Variables
        envFrom:
          - configMapRef:
              name: adcap-approval
          - configMapRef:
              name: adcap-approval-appdynamics
          - configMapRef:
              name: appdynamics-common
          - secretRef:
              name: appdynamics-secrets
        # End Modification-1
        env:
        - name: ROLE
          value: approval
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /hostroot
          name: hostroot
          readOnly: true
        - mountPath: /project
          name: project
        # Modification-2 - Add a Mount Path
        - mountPath: /opt/appdynamics-agents/java
          name: appd-agent-java-install
        # End Modification-2
      restartPolicy: Always
      volumes:
      - name: hostroot
        hostPath:
          path: /
          type: Directory
      - name: project
      # Modification-3 - Add a Container Volume
      - name: appd-agent-java-install
      # End Modification-3
      initContainers:
        - name: provider
          image: lincharles/adcapital-project:v01
          volumeMounts:
          - mountPath: /project
            name: project
        # Modification-4 - Add Second Initialization Container
        - name: appdynamics-java-agent
          image: appdynamics/java-agent:20.3.0
          imagePullPolicy: IfNotPresent
          command:
            - cp
            - -ra
            - /opt/appdynamics/.
            - /opt/appdynamics-agents/java/
          volumeMounts:
          - mountPath: /opt/appdynamics-agents/java
            name: appd-agent-java-install
        # End Modification-4
status: {}
# Define the Service for the approvals Pod
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: approval-v2
  name: approval-v2
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: approval-v2
status:
  loadBalancer: {}
