# Environment varibales requried for ADCAP approvals - Secret Base64 Encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  accesskey: "PGNvbnRyb2xsZXIgYWNjZXNzIGtleT4="
  accountname: "PGNvbnRyb2xsZXIgYWNjb3VudCBuYW1lIC0gc2hvcnQgbmFtZT4="
